### ISSUE TITLE
unable to see headers from backend server

### ISSUE THREAD

**Issue by listaction** [segpacto/gql-gateway#14]
hi @segpacto 
great product, but I am unable to see the headers returned by whatever is behind graphql (some headers / cookies returned).

Could you please let us know how to pass these back to the client / ui? (client >> ui) ?

**Comment by segpacto** [comment]
hello @listaction 
First thanks for feedback.
then, replying to your question, the package itself doesnt forward back the headers obtained from the final OpenApi service.
This is because in theory is requesting from several different endpoints and then creating an aggregation between schemas from different remote services, on this case the package would not be able to distinguish from which of this services(to which we requested data) it should forward back the headers. 
However, it is an interesting Feature. How would you choose which service headers to forward back on the response ?

**Note**: Take into consideration that the package allows to inject middlewares/plugins to the apollo server using `apolloServerConfig` property :

```
const resolvers = /***/
const localSchema = /**/
const endpointsList = /**/
const apolloServerConfig = { playground: { endpoint: /**/ } }

gateway({ resolvers, localSchema, endpointsList, apolloServerConfig })
.then(/**/)
```

**Comment by listaction** [comment]
Most backend services will be authenticated, so a standard `Authorization` and cookies should be allowed to passthrough back to the frontend. How can I do that here? an example would be great. (I do understand your point about allowing the some one to specify what to passback)

In my case the backend responds with Authorization: Bearer <token> like the one specified here: https://tools.ietf.org/html/rfc6750#section-2.1

**Comment by listaction** [comment]
@segpacto any ideas? I tried this but I don't see the backend headers in this.
```
const apolloServerConfig = {
  // ...,
  plugins: [
    {
      requestDidStart(requestContext) {
        return {
          willSendResponse(requestContext) {
            console.log(requestContext.response.http.headers);
          }
        }
      }

    }
  ]
}

gateway({ endpointsList, apolloServerConfig})
```

**Comment by listaction** [comment]
@segpacto  : fixed like this : please can you try and add it to your codebase - i can pr it - but you may have other plans.
https://github.com/dimacpp/gql

**Comment by segpacto** [comment]
@listaction 

The main goal of the package is to create relations among different remote services, it means that I will be relating apparently unrelated data from Ex: service pet and service fruits. Let's say hypothetically that I have a relation one to one between a Pet and a Product by the ids (totally unreal and from arch design wrong but just as an example of relation). So the same Id that identifies the Pet is going to identify the Product.
So, I decided to extend the Pet to also include a product property which comes with the product from the remote API.
Since the package is going to perform two request(One to get the Pet, another one to get the product based on the Pet response) then How the package is going to decide which headers to take and forward back to the client.

```
const gateway = require('gql-gateway')

const endpointsList = [
  { name: 'petstore_service', url: 'https://petstore.swagger.io/v2/swagger.json' },
  { name: 'fruits_service', url: 'https://api.predic8.de/shop/swagger' }
]
const apolloServerConfig = { 
  plugins: [
    {
      requestDidStart(requestContext) {
        return {
          willSendResponse(requestContext) {
            console.log('response >> ', requestContext.response);
          }
        }
      }
    }
  ]
}

const localSchema = `
  extend type Pet {
    product: Product
  }
`

const resolvers = {
    Pet: {
      product: {
        fragment: '... on Pet {id}',
        async resolve (pet, args, context, info) {
          const fruitSchema = await context.resolveSchema('fruits_service')
          
          return info.mergeInfo.delegateToSchema({
            schema: fruitSchema,
            operation: 'query',
            fieldName: 'getProductsId',
            args: {
              id: parseInt(pet.id)
            },
            context,
            info
          })
        }
      }
  }
}

gateway({ endpointsList, localSchema, resolvers, apolloServerConfig })
  .then(server => server.listen(4000))
  .then(console.log('Service is now running at port: 4000'))
  .catch(err => console.log(err))
```
If you take a look at the full example above you will notice that there are two responses.
For this reason I think your solution is proper to be applied to your solution however not sure it works the same for the whole package. We could be dealing with X amount of relations, that after retrieving the Pet, it could perform other requests to other external services to ask unrelated data with the Pet but related with the type of Pet it is. Then we could have infinite responses depending on the amount of relations.
If you have any specific way to deal with this issue we can discuss it.

**Comment by listaction** [comment]
hey @segpacto : sorry for not replying - I understand the ambiguity in what to expose , and that's where there is value. 

Perhaps, you can think of extending the part where you let users specify the  schema url to also include a function that can be provided by callers that can decide on these things - what headers to allow to be passed back to the frontend, and then you can invoke it to validate it in callbackend.js? I can raise a PR.

**Comment by segpacto** [comment]
Yes please, create a proposal. Is always welcome.
